KMOD=   i915kmsfw
FIRMWS= adlp_dmc_ver2_16.bin:i915_/dlp_dmc_ver2_16.bin \
	adlp_dmc_ver2_12.bin:i915_/dlp_dmc_ver2_12.bin \
	adlp_guc_62.0.3.bin:i915/adlp_guc_62.0.3.bin adlp_guc_70.bin:i915/adlp_guc_70.bin \
	tgl_huc_7.9.3.bin:i915/tgl_huc_7.9.3.bin
.include <bsd.kmod.mk>
